/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <CoreGraphics/CoreGraphics.h>

typedef struct RSTableData RSTableData;

/**
 * A simple pain-free pointer to wrap your types in for FFI export.
 */
typedef struct RSPointer_TableData
{
  struct RSTableData *ptr;
} RSPointer_TableData;

void test_rust_function(void);

struct RSPointer_TableData rs_init_table_data(void);
